const products = [
    {
        id: 1,
        name: "Wireless Headphones",
        description: "High-quality wireless headphones with noise cancellation.",
        price: 149.99,
        image: "wireless_headphones.jpg",
        category: "Electronics",
        stock: 25,
        rating: 4.5,
        brand: "SoundWave",
        tags: ["audio", "wireless", "headphones", "electronics"],
    },
    {
        id: 2,
        name: "Smart Watch",
        description: "Track your fitness and stay connected with this sleek smartwatch.",
        price: 199.99,
        image: "smart_watch.jpg",
        category: "Wearables",
        stock: 50,
        rating: 4.7,
        brand: "TechPro",
        tags: ["watch", "smart", "wearables", "fitness"],
    },
    {
        id: 3,
        name: "4K Ultra HD TV",
        description: "Experience stunning visuals with this 65-inch 4K Ultra HD TV.",
        price: 999.99,
        image: "4k_tv.jpg",
        category: "Electronics",
        stock: 15,
        rating: 4.8,
        brand: "VisionMax",
        tags: ["tv", "electronics", "4K", "home"],
    },
    {
        id: 4,
        name: "Gaming Laptop",
        description: "Powerful gaming laptop with high-end graphics and performance.",
        price: 1499.99,
        image: "gaming_laptop.jpg",
        category: "Computers",
        stock: 10,
        rating: 4.9,
        brand: "GamerX",
        tags: ["gaming", "laptop", "computers", "performance"],
    },
    {
        id: 5,
        name: "Bluetooth Speaker",
        description: "Portable Bluetooth speaker with excellent sound quality.",
        price: 79.99,
        image: "bluetooth_speaker.jpg",
        category: "Audio",
        stock: 100,
        rating: 4.4,
        brand: "BeatBoom",
        tags: ["audio", "bluetooth", "speaker", "portable"],
    },
    {
        id: 6,
        name: "Digital Camera",
        description: "Capture stunning photos with this 20 MP digital camera.",
        price: 549.99,
        image: "digital_camera.jpg",
        category: "Cameras",
        stock: 30,
        rating: 4.6,
        brand: "PhotoTech",
        tags: ["camera", "photography", "digital", "electronics"],
    },
    {
        id: 7,
        name: "Electric Scooter",
        description: "Eco-friendly electric scooter with a 25 km range.",
        price: 499.99,
        image: "electric_scooter.jpg",
        category: "Outdoor",
        stock: 8,
        rating: 4.3,
        brand: "EcoRide",
        tags: ["scooter", "electric", "outdoor", "transportation"],
    },
    {
        id: 8,
        name: "Smartphone",
        description: "Latest generation smartphone with a stunning display and powerful processor.",
        price: 899.99,
        image: "smartphone.jpg",
        category: "Phones",
        stock: 40,
        rating: 4.7,
        brand: "MegaPhone",
        tags: ["phone", "smartphone", "mobile", "electronics"],
    },
    {
        id: 9,
        name: "Fitness Tracker",
        description: "Track your activity and health metrics with this fitness tracker.",
        price: 59.99,
        image: "fitness_tracker.jpg",
        category: "Wearables",
        stock: 120,
        rating: 4.2,
        brand: "FitLife",
        tags: ["fitness", "tracker", "wearables", "health"],
        description: "Experience stunning visuals with this 55-inch 4K Ultra HD TV.",
        price: 799.99,
        image: "4k_tv.jpg",
        category: "Electronics",
        stock: 15,
        rating: 4.8,
        brand: "VisionTech",
        tags: ["tv", "4k", "electronics", "home"],
    },
    {
        id: 4,
        name: "Gaming Laptop",
        description: "High-performance gaming laptop with the latest graphics card.",
        price: 1299.99,
        image: "gaming_laptop.jpg",
        category: "Computers",
        stock: 10,
        rating: 4.6,
        brand: "GamerZone",
        tags: ["laptop", "gaming", "electronics", "computers"],
    },
    {
        id: 5,
        name: "Bluetooth Speaker",
        description: "Portable Bluetooth speaker with crystal-clear sound and deep bass.",
        price: 79.99,
        image: "bluetooth_speaker.jpg",
        category: "Audio",
        stock: 40,
        rating: 4.4,
        brand: "BassBlast",
        tags: ["audio", "bluetooth", "speaker", "electronics"],
    },
    {
        id: 6,
        name: "Wireless Mouse",
        description: "Ergonomic wireless mouse with adjustable DPI settings.",
        price: 29.99,
        image: "wireless_mouse.jpg",
        category: "Accessories",
        stock: 100,
        rating: 4.3,
        brand: "TechComfort",
        tags: ["mouse", "wireless", "computers", "accessories"],
    },
    {
        id: 7,
        name: "Fitness Tracker",
        description: "Water-resistant fitness tracker with heart rate monitor and sleep tracking.",
        price: 59.99,
        image: "fitness_tracker.jpg",
        category: "Wearables",
        stock: 75,
        rating: 4.2,
        brand: "FitLife",
        tags: ["fitness", "tracker", "wearables", "health"],
    },
    {
        id: 8,
        name: "DSLR Camera",
        description: "Capture stunning photos and videos with this high-resolution DSLR camera.",
        price: 999.99,
        image: "dslr_camera.jpg",
        category: "Cameras",
        stock: 8,
        rating: 4.7,
        brand: "CapturePro",
        tags: ["camera", "dslr", "photography", "electronics"],
    },
    {
        id: 9,
        name: "Gaming Chair",
        description: "Comfortable gaming chair with adjustable armrests and lumbar support.",
        price: 249.99,
        image: "gaming_chair.jpg",
        category: "Furniture",
        stock: 20,
        rating: 4.5,
        brand: "GamerGear",
        tags: ["chair", "gaming", "furniture", "comfort"],
    },
    {
        id: 10,
        name: "Smart Home Speaker",
        description: "Control your home with voice commands using this smart speaker.",
        price: 129.99,
        image: "smart_speaker.jpg",
        category: "Smart Home",
        stock: 30,
        rating: 4.6,
        brand: "HomeControl",
        tags: ["smart home", "speaker", "voice control", "electronics"],
    }
];

export default products;
